### ISSUE TITLE
J2ObjC_source.h file not found

### ISSUE THREAD

**Issue by conky2** [lukhnos/LuceneSearchDemo-iOS#3]
I followed the instructions and then attempted to build in Xcode but get the following error from Xcode: J2ObjC_source.h file not found

This error is thrown from the lucenestudy subproject.

**Comment by lukhnos** [comment]
It wasn't clear in the subproject's README, but [the mobile branch of lucenestudy](https://github.com/lukhnos/lucenestudy/tree/mobile) has its own J2ObjC prerequisites, and you have to run the [setup script](https://github.com/lukhnos/lucenestudy/blob/mobile/setup-j2objc.sh) under the subproject to have the J2ObjC requirement properly set up (or you can do the symbolic link yourself, since it makes no sense to download two copies of J2ObjC).

**Comment by conky2** [comment]
This is what I figured.  I actually tried manually doing the setup for both
and it did not work.  Still threw the same error.

**Comment by conky2** [comment]
If it's helpful, I've attached a screenshot of the error below.  I just re-tried this process and download j2ObjC in both lucenestudy and the base dir and am still getting the error as shown.  I very much appreciate your help.

![screen shot 2017-01-10 at 7 42 56 pm](https://cloud.githubusercontent.com/assets/25021281/21830774/1c1b53e8-d76d-11e6-98fb-4aa5b6366eda.png)

**Comment by conky2** [comment]
To the extent that it is helpful to anyone, follow these steps to build
(which worked for me):

1.  Follow the README instructions as written
2.  Download/create a link in the lucenestudy/vendor folder to the j2objc
(as mentioned by the author)
3.  Select "yes" under Build Settings/Swift Legacy
4.  Run Product/Clean in Xcode
5.  Build

Thanks to the author for his help and for posting this project.  Really
interesting/impressive to see Lucene in action on iOS.

**Comment by lukhnos** [comment]
I wrote the steps I used in #4, and I actually let Xcode upgrade Swift for the code.

One thing I noticed from your screenshot is that you were building the app as a macOS app. That wouldn't work and might explain some of the build issues you ran into. Compare my screenshot in #4 and you'll see the difference.
